### ISSUE TITLE
Auto registration/configuration of filters

### ISSUE THREAD

**Issue by mmoayyed** [apereo/java-cas-client#144]
Presently, filters need to be statically defined in the webapp context. This is cumbersome. It would be loads better if the client could auto-register itself, taking advantage of the new servlet API, and specially if it was then able to pick up url patterns from the configuration external to the app context. This would practically make client deployments so much easier because all required would be a jar drop-in.

I think a requirement for this approach is an upgrade to the existing servlet-api, or perhaps, we could incorporate these changes inside a separate module that does expect that api though I think providing support for this sort of thing inside the core jar is much easier for a deployer.

**Comment by mmoayyed** [comment]
I started playing around with `@WebFilter` of the servlet spec. With the right annotations in place, I was able to reduce my configuration down to:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="2.4" xmlns="http://java.sun.com/xml/ns/j2ee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd" metadata-complete="true">

    <context-param>
      <param-name>configurationStrategy</param-name>
      <param-value>PROPERTY_FILE</param-value>
    </context-param>

    <context-param>
        <param-name>configFileLocation</param-name>
        <param-value>/etc/cas/casclient.properties</param-value>
    </context-param>
</web-app>
```

This is cool, if I may say so!

This is a mode where the webapp is told that it should look into JAR libraries and scan the context for relevant annotations. This is done via `metadata-complete="true"`. When true, the context is scanned and filters are added automatically. The automation process (which is my own doing now) simply registers each filter by its class name, and then maps to a generic `/*` pattern. 

The default behavior of the metadata-complete tag is of course `false`, meaning everything needs to be done manually, just like it is today. 

The only complication is the mixture of both methods, where you have the filter registered dynamically, but may want to adjust urls its mapped to. This cannot be done, and either you use the default config, or your skip that altogether and register filters manually. (I don't think this is a big deal at all, and `/*` seems like a safe default bet and if needed, patterns can be excluded via the native client config)

**Comment by mmoayyed** [comment]
In fact, I probably could:

1. Get rid of the properties file reference
2. For 3.5, we may want to think about switching the default strategy option to be based on a property file. That would make it a total drop-in integration.

**Comment by mmoayyed** [comment]
Further experiments show that annotations aren't in fact enough because we can't quite control the order of those without resorting to xml config and overall, it is confusing to determine exactly which filter is defined and how. So while it may be enough for super simple use cases, it reality, it's still very immature.

An alternative would be to do this sort of thing via Spring Boot, and register filters and mappings directly via Java beans and such where we'd be granted total control of what works and what does not. I suppose it might be reasonable to add a "boot" module to the project here and handle the task separate from core and everything else.

**Comment by dima767** [comment]
An example how it's done via Spring Boot: https://github.com/Unicon/cas-client-autoconfig-support

**Comment by kakawait** [comment]
In addition I wrote my own Spring boot CAS starter https://github.com/kakawait/cas-security-spring-boot-starter. The main difference with [Unicon starter](https://github.com/Unicon/cas-client-autoconfig-support) is https://github.com/kakawait/cas-security-spring-boot-starter is fully integrated with **Spring security** and not only register filters.

Depends if you're **Spring security** user I could be a great advantage.
