### ISSUE TITLE
Filter crashes without any messages

### ISSUE THREAD

**Issue by wrighting** [apereo/java-cas-client#149]
I have a working configuration using version 3.2.2 and the filter org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter

If I either upgrade the version to either 3.3.3 or 3.4.1 or change to org.jasig.cas.client.validation.Cas30ProxyReceivingTicketValidationFilter then the application will not start

The only error message I see in the logs is:
org.apache.catalina.core.StandardContext startInternal SEVERE: Error filterStart

Logging is set at trace level

Using https://code.google.com/p/pwm/ version 1.6.4

**Comment by serac** [comment]
With 3.4.x, you'll need to define a new context parameter:

    <context-param>
      <param-name>configurationStrategy</param-name>
      <param-value>WEB_XML</param-value>
    </context-param>

No idea what's wrong with 3.3.x, but I'd focus on getting it working with 3.4.1.

**Comment by wrighting** [comment]
Thanks for the quick response but still crashes in the same way after adding that section to the web.xml (according to the readme it should use DEFAULT if none defined)

**Comment by mmoayyed** [comment]
What is the container version? What logs are you checking?

**Comment by wrighting** [comment]
There's a CAS server running in the same tomcat so:
Ubuntu 14.04 - Tomcat 7.0.52
```
2016-01-11 12:47:06,632 INFO [org.jasig.cas.CasEnvironmentContextListener] - <
******************** Welcome to CAS ********************
CAS Version: 4.1.3
Java Home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Java Vendor: Oracle Corporation
Java Version: 1.7.0_91
OS Architecture: amd64
OS Name: Linux
OS Version: 3.13.0-68-generic
*******************************************************
>
```
The client application has the following log4j configuration:
```
    <category name="org.jasig.cas.client">
        <priority value="trace"/>
        <appender-ref ref="CASfileLogger"/>
    </category>
```

That file is empty.

**Comment by mmoayyed** [comment]
You need to check your tomcat logs. Not the client app. The app is not loading, so its log file empty.

**Comment by wrighting** [comment]
The only thing of relevance in the tomcat logs (catalina.out) is:
```
Jan 11, 2016 12:47:43 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error filterStart
Jan 11, 2016 12:47:43 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/pwm] startup failed due to previous errors
```

**Comment by mmoayyed** [comment]
And there are no other log files? There is usually a localhost file.

**Comment by wrighting** [comment]
The localhost file does look more useful - not something I've seen very often

```
java.lang.IllegalArgumentException: Renew MUST be specified via context parameter or JNDI environment to avoid misconfiguration.
```

I tried adding the following to the web.xml without success
```
	<context-param>
		<param-name>renew</param-name>
		<param-value>false</param-value>
	</context-param>
```

**Comment by serac** [comment]
You need to remove all instances of renew init parameters in your web.xml. It defaults to false; you would only need to add the context param if you want to enable forced authentication.

**Comment by wrighting** [comment]
That's done it - many thanks.

For reference I also added casServerUrlPrefix init-param to the single sign out filter which is now mandatory and wasn't before.

Also it seems to work without configurationStrategy being defined.

I logged this as an issue because of the upgrade not working and no obvious clues in the documentation. (also my fault for only looking in catalina.out and application logs)

Perhaps change to
```
Note that renew can only be specified as a context-param setting. The application will not start if it is an init-param (post 3.2).
```

**Comment by battags** [comment]
Hi,

configurationStrategy should be optional (we default to one that checks all of the methods in the same order as older versions of the client).

Where are you suggesting we change the "renew" text?  In the error message or documentation? (I'm not against clarifying, just not sure where you were referring to :-))

Thanks
Scott

**Comment by wrighting** [comment]
I was suggesting in the documentation - it's useful to see what needs to change when upgrading -  but the error message could be improved as well.
(especially when working with a config that somebody else has put together e.g. https://github.com/pwm-project/pwm/blob/master/src/main/webapp/WEB-INF/web.xml)

The intention is to make it clear that you **must** not have renew as an init-param. With a table containing parameters that can mostly be either init or context, for me at least, it's easy to miss the distinction even with the existing text, which is clearer now!
It is hard to come up with something short and sufficiently descriptive either in error messages or docs.

It's not ideal that upgrading the jar causes the application to not start, but it is understandable, however I have put off upgrading this jar for a while as it wasn't immediately straightforward.
Of course it doesn't help when you forget to look at the log that contains something useful... - if you find a clue in the log then it helps when you go to the docs.

Thanks

**Comment by serac** [comment]
@battags, I found that parameter was required. I believe I did that analysis on a version prior to 3.4.1 final, so perhaps the backward compatibility was added subsequently and I missed it. Do we have test coverage for a web.xml that lacks configurationStrategy=WEB_XML?
