### ISSUE TITLE
Tomcat 8 client

### ISSUE THREAD

**Issue by BernhardLenz** [apereo/java-cas-client#150]
The tomcat 7 client doesn't run on 8 or 9 anymore since apache made some minor modifications. I created a local clone with a new cas-client-integration-tomcat-v8 subproject. In this I made 3 changes to the AbstractAuthenticator. 

1. Line 97
from 
            CommonUtils.assertTrue(realm instanceof CasRealm, "Expected CasRealm but got " + realm.getInfo());
to
            CommonUtils.assertTrue(realm instanceof CasRealm, "Expected CasRealm but got " + realm.getClass());

2. Line 153/154
from 
    public final boolean authenticate(final Request request, final HttpServletResponse response,
            final LoginConfig loginConfig) throws IOException {
to
    public final boolean authenticate(final Request request, final HttpServletResponse response) throws IOException {

3. Line 187
from 
    protected synchronized void setState(LifecycleState state, Object data) {
to 
    protected synchronized void setState(LifecycleState state, Object data) throws LifecycleException {

The master and cas-client-integration-tomcat-v8 pom.xmls were updated accordingly. 

Since I'm not a contributor I'm not able to push the changes. Could you please incorporate the changes into the project? 

Sincerely
Bernie

**Comment by mmoayyed** [comment]
You are going to want to submit a pull request instead. Changes are not pushed directly.

**Comment by mmoayyed** [comment]
https://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request

**Comment by BernhardLenz** [comment]
Thanks. Indeed I'm not a git guru. I created a folk, branch, commited and pushed my changes and then created the pull request in my folk. 

Hope this works....

**Comment by BernhardLenz** [comment]
I saw that pull request #151 failed because build #62 failed. The failure is in cas-client-core which is something that I haven't touched. I'm assuming this is an existing problem on the baseline code base. How to go about it?

**Comment by mmoayyed** [comment]
- Run tests from the command line and see if you can reproduce the failure with your branch. 
- Run tests from the command line and see if you can reproduce the failure with master. 

Compare changes.

**Comment by BernhardLenz** [comment]
I see the build ran again just now and it passed all the checks. Not sure what the problem was but I think all is good now.

**Comment by battags** [comment]
This was merged in.
