### ISSUE TITLE
Jetty Container Integration

### ISSUE THREAD

**Issue by serac** [apereo/java-cas-client#152]
It would be nice to have container-based authentication for Jetty similar to what we already have for Tomcat.

**Comment by serac** [comment]
Jetty integration pull request has been accepted and merged into master.

**Comment by mmoayyed** [comment]
README likely should be updated.

**Comment by serac** [comment]
Reopening until I update docs.

**Comment by battags** [comment]
Did you get a chance to update the docs? :-D

**Comment by serac** [comment]
Goal is to complete by end of week.

**Comment by msteiger** [comment]
Are you going to create an artifact for it as well or how do I integrate it in my application?

**Comment by battags** [comment]
An artifact is automatically created when we cut a release.  I'm thinking we should cut one soon.  @serac  did you get a chance to update the documentation?

**Comment by serac** [comment]
I'll add some documentation today.

**Comment by serac** [comment]
Docs updated in 13fa0d0.

**Comment by msteiger** [comment]
Thanks! It would be great to have a release with the new Jetty client packaged :smile:
