### ISSUE TITLE
assertion.isValid() incorrectly handles date comparisons?

### ISSUE THREAD

**Issue by mmoayyed** [apereo/java-cas-client#154]
I have this:

```java
        final Assertion assertion = validator.validate(ticket, serviceUrl);
        logCasValidationAssertion(assertion);
        if (!assertion.isValid()) {
           failMiserably();
        }
```

where `isValid` does this:

```java

    public boolean isValid() {
        if(this.validFromDate == null) {
            return true;
        } else {
            Date now = new Date();
            return this.validFromDate.before(now) && (this.validUntilDate == null || this.validUntilDate.after(now));
        }
    }
```
isValid() call fails at random. I traced it down:

![image](https://cloud.githubusercontent.com/assets/1205228/13553481/76f14fc6-e348-11e5-9864-8f63d87d4be2.png)

As you see, my validFromDate is `Sun Mar 06 03:02:06 MST 2016`. As it turns out, my `now` is exactly the same. Yet `this.validFromDate.before(now)` is always false. 

I think it's because the comparison is done at the millisecond level. This is not practical.

**Comment by battags** [comment]
To be slightly pedantic, if they're failing then they're not exactly the same (regardless of what the toString() shows) :-)

That said, you're basically asking if the check is too precise.  Are you suggesting that we zero out the milliseconds in the "now" ?

**Comment by mmoayyed** [comment]
Yes that's exactly my point. Too precise. Your suggestion should work but I am also thinking whether we should allow for a time skew. That's a fairly common solution when dealing with time synchronization issues across different timezones, etc (though in my case there was none).

**Comment by mmoayyed** [comment]
My solution right now is to pause the active thread for 1 millisecond before checking for validity. If you could skew the comparison by that much, things should be fine, but the skew should be configurable.

**Comment by mmoayyed** [comment]
I was planning to issue a PR for this, but this sort of begs the question: @battags are you planning to move to Java 8? If so, I guess we could handle such comparisons better with the Date/Time API of 8. Otherwise, I could massage the check a bit here to be more relaxed.

**Comment by battags** [comment]
I don't see why we would move to require Java 8 yet.  We'd be limiting the number of people who could use the more recent versions of this client just so that internally we could use the newer date API.

**Comment by laimoncijus** [comment]
Seems I am having the same issue with CAS client v. 3.4.1 and Java 8. 

Are there plans for solving this issue? Maybe you could give a comment on this, thanks!

**Comment by battags** [comment]
@mmoayyed do you have a non-Java 8 specific fix already prepared?

**Comment by mmoayyed** [comment]
I should have a simple solution for this soon. Testing the patch before I submit.
