### ISSUE TITLE
Move to Apereo?

### ISSUE THREAD

**Issue by mmoayyed** [apereo/java-cas-client#160]
@battags We might want to move the client repo over to Apereo. Would you be OK if I started the move late tomorrow evening EDT? Would you rather stay here?

**Comment by battags** [comment]
I think it makes sense to move it over if you're willing to do it :-)  Thanks!

**Comment by mmoayyed** [comment]
Viola! Here we are :)

Shall I rename this issue to be "Rename all org.jasig to org.apereo"? Do we want to target that for a 3.5?

**Comment by dima767** [comment]
I think `3.5` would be a logical version for this, unless you want to name the version as `4.0` to reflect a major package re-name. @battags - 4.0 vs 3.5 , what do you say? ;-)

**Comment by mmoayyed** [comment]
@battags Question: is master moving towards 3.5 or 3.4.2? Shall we branch 3.4 and let master be 3.5?

**Comment by dzj2046** [comment]
I suggest client version also be 5.0
