### ISSUE TITLE
Dynamic service url

### ISSUE THREAD

**Issue by fabiowg** [apereo/java-cas-client#164]
From what I have read about CAS, it seems that every web service is supposed to be accessed by a single URL. Where I work it's quite common to access our applications (usually deployed in our clients' servers) using different URLs, particulary when users want to access them via internet or their intranet.

We've been running some POCs to validate if we could use CAS as our SSO solution, but this "limitation" of a single URL per service can be a bit troublesome considering our current practices, so I ended up patching the CAS client code to consider the URL accessed by the user to resolve the service URL (and also the CAS server URL). Since security isn't our expertise, we're wondering if this approach could open breaches of security. Could you please explain the reasoning behind the idea of a single URL per service?

I will submit a pull request with this patch just in case my explanation wasn't clear enough. Thanks for your attention!

**Comment by mmoayyed** [comment]
There is no "single URL per service" unless you configure the client to use a static URL in the config.

**Comment by fabiowg** [comment]
@mmoayyed, thanks for your answer!

In this case, how should I configure the tomcat context?

Currently it's something like this:

    <Realm className="org.jasig.cas.client.tomcat.v7.AssertionCasRealm" roleAttributeName="role"/>

    <Valve className="org.jasig.cas.client.tomcat.v7.SingleSignOutValve"
    artifactParameterName="SAMLart"
    />

    <Valve className="org.jasig.cas.client.tomcat.v7.Saml11Authenticator"
    encoding="UTF-8"
    casServerLoginUrl="https://abc.com/cas/login"
    casServerUrlPrefix="https://abc.com/cas/"
    serverName="abc.com"
    />

**Comment by mmoayyed** [comment]
I must admit I have not done much with the tomcat client. What do you consider static in that configuration? All I see is `abc.com`. service urls are constructed dynamically, or they should be, based on this server name. That not happening? Or you wish to change the server name dynamically?

**Comment by fabiowg** [comment]
Yes, service urls are constructed dynamically based on this server name, but yes, I wish the server name wasn't hard-coded but based on the url accessed by the user. We have some clients where the users access the server using it's IP address, say, 123.12.3.4, when connected to their intranet, but access it using a domain like abc.com when anywhere else.

**Comment by mmoayyed** [comment]
This sort of change probably have to be done as an extension for your environment only, because the client surely can never trust anything that comes from the user.

**Comment by battags** [comment]
CAS Client already supports multiple host names if you put them in the
serverName field separated by a space.

**Comment by fabiowg** [comment]
Thanks again for your answers!

@battags, I checked out some of your commits (e055585c, fb42fefa, eff195aa), and it seems to me that they would indeed solve part of my issue! However, I'm still facing some problems:

First, I'm trying to setup and environment with an old version of the client (3.2.2) because the newer versions would force us to bring some dependencies that conflicts with ours. I could port those commits to the branch 3.2.x if you think that's a good idea (I have serious doubts anyone would still be worried with this old branch, though).

The second problem concerns the url of the CAS server itself: with your commits, only our applications could be accessed by different host names, but the CAS server would still have to be hard-coded in our context.xml. If a user accessed our application typing 123.12.3.4/app, I'd like him to be redirected to 123.12.3.4/cas, and if he accessed typing abc.com/app, I'd like him to be redirected to abc.com/cas.

Is it possible to achieve this kind of behavior using the newer versions of the client?
