### ISSUE TITLE
[SLO[SLO] SingleSignOutFilter throws exception when login under clustered CAS client environment

### ISSUE THREAD

**Issue by richardwei2008** [apereo/java-cas-client#173]
Problem Description:

SingleSignOutFilter throws exception while access clustered CAS client application as below, but when CAS client application runs on single node, everything works fine:

HTTP Status 500 -

type Exception report

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 500 for URL: https://nsso.net/cas/proxyValidate?ticket=ST-443-1D0pMMe9R2f3iVfFvfpS-nsso215.net&service=http%3A%2F%2Fxxx.net%2Fmiser-biz-web%2Flogin%2FviaCas.action%3Bjsessionid%3D167441E9B9CF3756EDC23F20A1965C67.83
	org.jasig.cas.client.util.CommonUtils.getResponseFromServer(CommonUtils.java:443)
	org.jasig.cas.client.validation.AbstractCasProtocolUrlBasedTicketValidator.retrieveResponseFromServer(AbstractCasProtocolUrlBasedTicketValidator.java:41)
	org.jasig.cas.client.validation.AbstractUrlBasedTicketValidator.validate(AbstractUrlBasedTicketValidator.java:193)
	org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:204)
	org.jasig.cas.client.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:164)
	org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:97)
	org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
root cause

java.io.IOException: Server returned HTTP response code: 500 for URL: https://nsso.net/cas/proxyValidate?ticket=ST-443-1D0pMMe9R2f3iVfFvfpS-nsso215.net&service=http%3A%2F%2Fxxx.net%2Fmiser-biz-web%2Flogin%2FviaCas.action%3Bjsessionid%3D167441E9B9CF3756EDC23F20A1965C67.83
	sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1436)
	sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:234)
	org.jasig.cas.client.util.CommonUtils.getResponseFromServer(CommonUtils.java:431)
	org.jasig.cas.client.validation.AbstractCasProtocolUrlBasedTicketValidator.retrieveResponseFromServer(AbstractCasProtocolUrlBasedTicketValidator.java:41)
	org.jasig.cas.client.validation.AbstractUrlBasedTicketValidator.validate(AbstractUrlBasedTicketValidator.java:193)
	org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:204)
	org.jasig.cas.client.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:164)
	org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:97)
	org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
note The full stack trace of the root cause is available in the JBoss Web/2.1.12.GA-patch-03 logs.

JBoss Web/2.1.12.GA-patch-03

Web.xml follows:

	<listener>
    	<listener-class>org.jasig.cas.client.session.SingleSignOutHttpSessionListener</listener-class>
	</listener>
	<filter>
   		<filter-name>CAS Single Sign Out Filter</filter-name>
   		<filter-class>org.jasig.cas.client.session.SingleSignOutFilter</filter-class>
   		<init-param>
      		<param-name>casServerUrlPrefix</param-name>
      		<param-value>https://nsso.net/cas</param-value>
   		</init-param>
	</filter>
	<filter-mapping>
   		<filter-name>CAS Single Sign Out Filter</filter-name>
   		<url-pattern>/*</url-pattern>
	</filter-mapping>

	<filter>
		<filter-name>CAS Validation Filter</filter-name>
		<filter-class>org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter</filter-class>
		<init-param>
			<param-name>casServerUrlPrefix</param-name>
			<param-value>https://nsso.net/cas</param-value>
		</init-param>
		<init-param>
			<param-name>serverName</param-name>
			<param-value>https://xxx.net</param-value>
		</init-param>
		<init-param>
			<param-name>redirectAfterValidation</param-name>
			<param-value>true</param-value>
		</init-param>
		<init-param>
			<param-name>useSession</param-name>
			<param-value>true</param-value>
		</init-param>
		<init-param>
			<param-name>acceptAnyProxy</param-name>
			<param-value>true</param-value>
		</init-param>
		<init-param>
			<param-name>encoding</param-name>
			<param-value>UTF-8</param-value>
		</init-param>
	</filter>
	
	<filter>
		<filter-name>CAS Authentication Filter</filter-name>
		<filter-class>org.jasig.cas.client.authentication.AuthenticationFilter</filter-class>
		<init-param>
			<param-name>casServerLoginUrl</param-name>
			<param-value>https://nsso.net/cas/login</param-value>
			
		</init-param>
		<init-param>
			<param-name>serverName</param-name>
			<param-value>https://xxx.net</param-value>
		</init-param>
	</filter>

	<filter>
		<filter-name>CAS HttpServletRequest Wrapper Filter</filter-name>
		<filter-class>org.jasig.cas.client.util.HttpServletRequestWrapperFilter</filter-class>
	</filter>

	<filter-mapping>
		<filter-name>CAS Validation Filter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
	<filter-mapping>
		<filter-name>CAS Authentication Filter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
	<filter-mapping>
		<filter-name>CAS HttpServletRequest Wrapper Filter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>

The logical architecture like
![cluster_architecture](https://cloud.githubusercontent.com/assets/1597335/17009798/d246a8d6-4f30-11e6-8103-36fb532b6884.png)

There is a nginx load balancer in front of both cas client cluster and cas server cluster.
I simplified the request flow as described in CAS offical document.

![image](https://cloud.githubusercontent.com/assets/1597335/17009862/6361e4f2-4f31-11e6-9284-e4f71676b0ca.png)

**Comment by battags** [comment]
You server-side threw an exception:
java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 500 for URL: https://nsso.net/cas/proxyValidate?ticket=ST-443-1D0pMMe9R2f3iVfFvfpS-nsso215.net&service=http%3A%2F%2Fxxx.net%2Fmiser-biz-web%2Flogin%2FviaCas.action%3Bjsessionid%3D167441E9B9CF3756EDC23F20A1965C67.83

Did you check your server logs?

**Comment by framillien** [comment]
Have you tried distribued cas client ? For Slo, cas server do some callbacks to cas client. But each cas client maintain  local ticket cache, and cas server can't target the right cas client node. So, tickets informations must be shared by all cas clients.

https://www.google.fr/url?q=https://wiki.jasig.org/plugins/servlet/mobile%23content/view/27035107&sa=U&ved=0ahUKEwi9pLr6xoTOAhUEDMAKHXFYAZUQFggNMAE&usg=AFQjCNHZQDWJVdVYyfvIKJ2Voqk70SNMlg

**Comment by richardwei2008** [comment]
@battags I can not find any internal exception from the two node CAS server cluster. But I do find a error on nginx server like:
[error] 73456#0: *33 upstream_jvm_route find the session in URI error!, client: 127.0.0.1, server: localhost, request: "GET /cas/proxyValidate?ticket=ST-1-QPcVSuU2VksKekVihBK7-cas01.sso.com&service=https%3A%2F%2Fapp1.com%3A8413%2Fcas1%3Bjsessionid%3DB7B65C4A9965E89106973B1477A28AB3.tomcat1 HTTP/1.1", host: "proxy.sso.com"

@framillien Thanks a lot. I spend an entire day to investigate the issue. Though I have not got chance to get a sound prove from network analysis, your reply actually speak out my guess.
