### ISSUE TITLE
Expose ProxyGrantingTicket from Assertion

### ISSUE THREAD

**Issue by kakawait** [apereo/java-cas-client#176]
In distributed environment or during batch processing that does not rely on Java, it can be interesting to share user ProxyGrantingTicket to retrieves ProxyTicket on other part of the system.

Actually in order to get PGT for a given user we need the PGTIOU that is not accessible either.

**Comment by mmoayyed** [comment]
PGTs can already be shared by the client, or is that not what you were asking?

**Comment by kakawait** [comment]
@mmoayyed Can you share with me a sample or API to use to retrieve PGT for the current session (without using PGTIOU)?

Because yes if possible it will match my use case because I just want to share the PGT to other batch service.

**Comment by mmoayyed** [comment]
Recent versions of the CAS server can put the PGT directly in the assertion as an attribute. So you want to start there, and once you have it, it's no different than getting any other attribute via the client. If you'd rather do proxy callbacks, then read on. 

If you want to share the PGT across nodes, then you want to look at the distributed ehcache or memcached modules of the client

**Comment by kakawait** [comment]
@mmoayyed Ok thank I about server side! It's easy to retrieve attribute. I'm just not the owner of server side I have to check with owner.

No is not about sharing PGT across nodes, this point is ok.

Thank
