### ISSUE TITLE
Every other request incorrectly gatewayed

### ISSUE THREAD

**Issue by OlivierJaquemet** [apereo/java-cas-client#177]
When using a gateway, request are not constantly being processed in the same way.

```
// First request not gatewayed
Session["_const_cas_gateway_"] = null
Request1 : AuthenticationFilter --> gateway.hasGatewayedAlready  // wasGatewayed = false
Session["_const_cas_gateway_"] = null
Request1 : AuthenticationFilter --> gateway.storeGatewayInformation                         
Session["_const_cas_gateway_"] = "yes"

// Second consecutive request, expected not to be gatewayed/redirected
Request2 : AuthenticationFilter --> gateway.hasGatewayedAlready  // wasGatewayed = true
Session["_const_cas_gateway_"] = null

// Third consecutive request, expected not to be gatewayed/redirected
// BUG ?? because request2 has invoked hasGatewayedAlready, the session attribute has been removed and a redirection occurs
Request3 : AuthenticationFilter --> gateway.hasGatewayedAlready  // wasGatewayed = false
Session["_const_cas_gateway_"] = null
Request3 : AuthenticationFilter --> gateway.storeGatewayInformation                         
Session["_const_cas_gateway_"] = "yes"
```

Possible explanation : 
DefaultGatewayResolverImpl.hasGatewayedAlready does not only read the session attribute, it also removes it, which may lead to concurrency issue if several request of the same session are 
run consecutively/concurrently ( see example for Request 1 and Request 2 below) 

Pull request with unittest and fix soon incomming...

**Comment by battags** [comment]
Hi --thanks for the bug report.  Are you saying you see this issue if two requests (using the same session) get triggered at once?

**Comment by serac** [comment]
I think you've identified legitimate problem related to the behavior under concurrent gateway requests, but I'm not sure we can fix it without tying the gateway request to the response using a unique identifier. By my reading of the v2 protocol spec [1], the following could be allowed:

    https://cas.example.com/login?service=https://example.com&gateway=10ef0c9

Then you could track gateway requests in the session using a Map keyed on the unique ID, but the CAS server would have to return the gateway parameter in the redirect to allow correlating request pairs. That seems like a reasonable change to properly fix this, but it's obviously bigger than a simple client patch.

[1] https://github.com/apereo/cas/blob/master/cas-server-documentation/protocol/CAS-Protocol-V2-Specification.md

**Comment by OlivierJaquemet** [comment]
@battags absolutely, consecutive or concurrent request of the same session. For example, it can occurs if a protected page includes other resources in a protected area. A fictive example would be something like : 
```
<html>
   [...]
    <script src="protected.js" type="text/javascript"></script>
    <link rel="stylesheet" href="protected.css" type="text/css" />
    <img src="protected-image.png" [...] />
   [...]
</html>
```

@serac I don't have enough knowledge and understanding of the protocol to see if it would be a correct approach.
Did you check my PR and the unittest ? Tying the check to a unique attribute of the session like the original implementation did seems just fine to me. The only mistake I could spot was removing this attribute for each request check.  I don't fully understand why the existing implementation was coded this way.

**Comment by serac** [comment]
@OlivierJaquemet I reviewed the PR and I don't think either the old unit test or the new one provide enough test coverage to adequately cover the myriad cases that can arise under concurrent requests. I _think_ your PR is an improvement in general, but it may be that it fixes one case while breaking another that I'm not seeing at the moment. Hopefully @battags has an opinion.

**Comment by OlivierJaquemet** [comment]
@serac @battags Any chance you might review this PR again ?

**Comment by OlivierJaquemet** [comment]
Please do not automatically close this issue and the associated PR. 

All the tests I have provided in the PR #178 still passes properly. The issue is real and the fix is working (and is in production for at least one of our customer !).

@serac you said in august 2016 that coverage was not enough and tried to reach @battags for code review. Unfortunately, even with a ping attempt in spt 2017, i could not get any indication of what was missing.

**Comment by OlivierJaquemet** [comment]
Thank you @mmoayyed
