### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by SaintSeraphim** [apereo/java-cas-client#179]
When I issue
mvn clean package

I get

P:\java-cas-client>mvn clean package
[INFO] Scanning for projects...
Downloading: http://10.1.0.204:8081/artifactory/libs-release/org/jasig/parent/ja
sig-parent/39/jasig-parent-39.pom
Downloading: http://10.1.0.204:8081/artifactory/libs-snapshot/org/jasig/parent/j
asig-parent/39/jasig-parent-39.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.jasig.cas.client:cas-client:3.4.2-SNAP
SHOT: Could not transfer artifact org.jasig.parent:jasig-parent:pom:39 from/to c
entral (http://10.1.0.204:8081/artifactory/libs-release): Connect to 10.1.0.204:
8081 [/10.1.0.204] failed: Connection timed out: connect and 'parent.relativePat
h' points at wrong local POM @ line 2, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.jasig.cas.client:cas-client:3.4.2-SNAPSHOT (P:\java-ca
s-client\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.jasig.cas.client:cas-client:3.4.2-
SNAPSHOT: Could not transfer artifact org.jasig.parent:jasig-parent:pom:39 from/
to central (http://10.1.0.204:8081/artifactory/libs-release): Connect to 10.1.0.
204:8081 [/10.1.0.204] failed: Connection timed out: connect and 'parent.relativ
ePath' points at wrong local POM @ line 2, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableMo
delException

**Comment by serac** [comment]
Please seek support on the mailing lists per instructions in following link:

https://apereo.github.io/cas/Mailing-Lists.html
