### ISSUE TITLE
Rework the front-channel logout functionality

### ISSUE THREAD

**Issue by mmoayyed** [apereo/java-cas-client#186]
The present front-channel logout functionality requires a bit of dancing around between the client app and the CAS server, where the sequence appears to be the following:
1. Receive a logout request as a GET
2. Kill session
3. Redirect back to CAS with a special URL allowing the server to proceed to the next entry. 

This is not practical. Instead, the server should issue async logout requests via JS to apps and track the completion status of the call. These requests are somewhat identical to the back-channel logout process, (method and payload) which should help simplify the conditional logic we have today (`isFrontChannel()` & `isBackChannel()` vs `IsLogoutRequest()`) .

**Comment by leleuj** [comment]
+1

**Comment by personal2santy** [comment]
I am trying to implement CAS SLO with logout type as FRONT_CHANNEL. Here is my setup,

I have a CAS server (version 4.2.3) and 2 CAS clients (spring security web apps) In CAS server, I have registered the 2 CAS clients with logout type as FRONT_CHANNEL

In the CAS client application, when I am singled signed on, i try to logout 1 CAS client application, it logouts the other application as well. Bingo!!! It works as I expected it to work.

However, when I have 3 CAS client applications (registered this in CAS server with FRONT_CHANNEL as logout type), and I try to do single logout, only 2 applications are logged out.

I understand that FRONT_CHANNEL is in experimental phase. Is this one of the limitation of FRONT_CHANNEL that it cannot single logout more than 2 applications?

Or am I missing something here?

Please help!

**Comment by mmoayyed** [comment]
Certainly not. All apps should log out. You'll need to look into the behavior of your 3rd client and see why it might be ignoring it. Short of that, it would be a bug.

**Comment by personal2saan** [comment]
I think this is a bug (If so, where should I log it). Here is the reason why I think based on the following test I did,

I had cas web applications app1, app2 and app3. I did a single sign on and was logged into all 3 apps. 

Tried the following scenarios,
1) I logged out of app1, it logged out app3 only and not app2
2) I logged out of app2, it logged out app1 only and not app3
3) I logged out of app3, it logged out app2 only and not app1. 

I also tried a scenario where I logged only into 2 applications (either app1 and app2 or app2 and app3 or app3 and app1)

In any possible combination, where there are only 2 apps logged in, I did not have any issues doing a single logout.

**Comment by mmoayyed** [comment]
I am not yet quite sure where the issue best may be logged. Could you provide logs for both CAS and the client app that should be logged out?

**Comment by personal2saan** [comment]
Logs attached.

[cas_client_app3.txt](https://github.com/apereo/java-cas-client/files/507104/cas_client_app3.txt)
[cas_server.txt](https://github.com/apereo/java-cas-client/files/507103/cas_server.txt)
[cas_client_app1.txt](https://github.com/apereo/java-cas-client/files/507105/cas_client_app1.txt)
