### ISSUE TITLE
Security issue: XXE (XML External Entity) security issue

### ISSUE THREAD

**Issue by raintung** [apereo/java-cas-client#191]
XmlUtils hard code the feature logic, only disable the namespace-prefix, and load-externam-dtd, but NOT prevent the XXE security issue.

public static XMLReader getXmlReader() {
        try {
            final XMLReader reader = SAXParserFactory.newInstance().newSAXParser().getXMLReader();
            reader.setFeature("http://xml.org/sax/features/namespaces", true);
            reader.setFeature("http://xml.org/sax/features/namespace-prefixes", false);
            reader.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
            return reader;
        } catch (final Exception e) {
            throw new RuntimeException("Unable to create XMLReader", e);
        }
    }

Should change to 
reader.setFeature("http://xml.org/sax/features/external-general-entities", false);
reader.setFeature("http://xml.org/sax/features/external-parameter-entities", false);

//Disable all doctype
reader.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);

The effect class:
SingleSignOutHandler
Cas20ServiceTicketValidator
Cas20ProxyRetriever

**Comment by attritionorg** [comment]
@battags I know this is an older issue, but I am trying to determine if this was ever resolved. The commits from CAS-Explorer that reference this suggest that upgrading to 3.5.0 fixes. However, I did not find any commits that reference this issue and don't see anything in the release notes. Can you or another contributor verify? Thanks!

**Comment by SxB64** [comment]
> XmlUtils hard code the feature logic, only disable the namespace-prefix, and load-externam-dtd, but NOT prevent the XXE security issue.
> 
> public static XMLReader getXmlReader() {
> try {
> final XMLReader reader = SAXParserFactory.newInstance().newSAXParser().getXMLReader();
> reader.setFeature("http://xml.org/sax/features/namespaces", true);
> reader.setFeature("http://xml.org/sax/features/namespace-prefixes", false);
> reader.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
> return reader;
> } catch (final Exception e) {
> throw new RuntimeException("Unable to create XMLReader", e);
> }
> }
> 
> Should change to
> reader.setFeature("http://xml.org/sax/features/external-general-entities", false);
> reader.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
> 
> //Disable all doctype
> reader.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
> 
> The effect class:
> SingleSignOutHandler
> Cas20ServiceTicketValidator
> Cas20ProxyRetriever

is this issue absolutely resovled?

**Comment by serac** [comment]
Reopening because the recommended fix, which is entirely reasonable, has not been applied. PR forthcoming...

**Comment by serac** [comment]
PR with fix: https://github.com/apereo/java-cas-client/pull/318
