### ISSUE TITLE
Support of SAML 2.0 ?

### ISSUE THREAD

**Issue by laurre** [apereo/java-cas-client#195]
I found documentation or modules for the server side, but I can't find any references to the SAML 2.0 protocol support in the client. In the cas-client-support-saml, I can only find SAML 1.1 related stuff. 

Is SAML 2.0 supported for a java CAS client ? 

Edit: I would find interesting to link in the documentation server components to client equivalents.

**Comment by dima767** [comment]
I don't think it's "supported". CAS5 acts as a standard SAML2 Identity Provider, so on the other side any available SAML2 SP libraries should do.

**Comment by dima767** [comment]
For example, on the Java SAML SP side, there is 👉 http://projects.spring.io/spring-security-saml/ You might want to try it to integrate with CAS5 SAML IDP server.
