### ISSUE TITLE
how can I set any value after cas login.

### ISSUE THREAD

**Issue by johnMaster** [apereo/java-cas-client#204]
- [4.2.7] CAS server version
- [Tomcat, java ] 

I have an old java web project, which is big.
before, i set some status value to session after user login.
but now, how can i set value to session after cas login with less proejct code alter

**Comment by mmoayyed** [comment]
Thank you for the issue submission. This seems like something that should be discussed on a mailing list or chatroom, etc.

**Comment by johnMaster** [comment]
I found that there is an `AbstractTicketValidationFilter` I can inherit it and rewrite `onSuccessfulValidation` method. so I can add status value to session in `onSuccessfulValidation` method . you save my days.
