### ISSUE TITLE
什么时候开始能支持免证书(nossl)访问

### ISSUE THREAD

**Issue by 15174834** [apereo/java-cas-client#205]
什么时候开始能支持免证书(nossl)访问

**Comment by dima767** [comment]
@serac or we could all learn Chinese 😁

**Comment by 15174834** [comment]
我是想问当client invoker cas服务的时候，会报https证书错误，你们可以做个不需要导证书的版本吗?

**Comment by richardwei2008** [comment]
@15174834 please read CAS user guide carefully. And you may find a way to support nossl access and ignore https. However, it is not recommended. You may only try it in non-production environment.

**Comment by 15174834** [comment]
Is it used to save session ?

**Comment by 15174834** [comment]
Okay, thank you
