### ISSUE TITLE
CAS Single Sign Out Filter and request.getInputStream

### ISSUE THREAD

**Issue by deo-prime** [apereo/java-cas-client#210]
when i configured the single sign out filter, in my servlet i can not read request.getInputStream, the stream contains value, but i can not read it. But when i delete single sign out filter, all works.
version: 3.3.3
jdk6/tomcat6

**Comment by mattdrees** [comment]
I ran into this as well.

The problem appears to be [here](https://github.com/apereo/java-cas-client/blob/cas-client-3.5.0/cas-client-core/src/main/java/org/jasig/cas/client/session/SingleSignOutHandler.java#L166); this "safeGetParameter" call triggers a `request.getParameter()` call, which causes the container to consume the input stream.

**Comment by mattdrees** [comment]
I commented 7 days ago. That doesn't count as recent activity?

**Comment by battags** [comment]
I don't really work on CAS any more but also commenting so that this doesn't go stale (since I'm still getting emails).  @mattdrees I see that you have a filter wrapper in your local repository.  Any chance that could just be folded into the existing filter and contributed as a pull request?

**Comment by mattdrees** [comment]
Yeah, good chance.
Though there has been other (non-cas) things blocking me from getting single-logout working, so I'm 100% sure mine is working. Does seem to at least prevent this issue, though.
