### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by Paul75** [apereo/java-cas-client#216]
Hello,

When I do : mvn clean package it do errors :

[main] ERROR org.jasig.cas.client.util.CommonUtils - Error getting response from host: [localhost] with path: [/validate] and protocol: [http] Error Message: Connexion refusée (Connection refused)
...

[main] ERROR org.jasig.cas.client.authentication.AuthenticationFilter - Could not instantiate class [unknown.class.name]
...

[main] INFO org.jasig.cas.client.jaas.CasLoginModule - Login failed due to CAS ticket validation failure: {}
org.jasig.cas.client.validation.TicketValidationException: Ticket ST-200000-aA5Yuvrxzpv8Tau1cYQ7-srv1 not recognized
...

[main] INFO org.jasig.cas.client.jaas.CasLoginModule - Login failed due to CAS ticket validation failure: {}
org.jasig.cas.client.validation.TicketValidationException: Ticket ST-300000-aA5Yuvrxzpv8Tau1cYQ7-srv1 not recognized

and others ....

Thanks

**Comment by mmoayyed** [comment]
Travis CI should be building master correctly. Please pull again and verify.

This is the build script: https://github.com/apereo/java-cas-client/blob/master/.travis.yml
