### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by jmvoisin** [apereo/java-cas-client#217]
Hi,
When i execute the command :  mvn clean package
I have the error : 

 ERROR org.jasig.cas.client.configuration.ConfigurationStrategyName - Unable to locate strategy bleh! by name or class name.  Using default strategy instead.

and 

java.lang.ClassNotFoundException: bleh!
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)

and finally :
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.6:test (default-test) on project cas-client-core: There are test failures.

I have just download and install the latest maven version and i have download with the git command line (git clone ...)

Could you help me please ?
Thanks

**Comment by mmoayyed** [comment]
Travis CI should be building master correctly. Please pull again and verify.

This is the build script: https://github.com/apereo/java-cas-client/blob/master/.travis.yml

**Comment by Paul75** [comment]
Hello,

Now with same comand it do :

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:2.2.1:jar (attach-sources) on project cas-client: Execution attach-sources of goal org.apache.maven.plugins:maven-source-plugin:2.2.1:jar failed: Plugin org.apache.maven.plugins:maven-source-plugin:2.2.1 or one of its dependencies could not be resolved: Failure to find classworlds:classworlds:jar:1.1-alpha-2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException`

Thanks
