### ISSUE TITLE
CAS SSO Isssue

### ISSUE THREAD

**Issue by satya410** [apereo/java-cas-client#218]
I'm using CAS 4 in my project. I've two applications. I successfully logged in to my application 1, If I redirect to application 2 from application 1 then CAS is forced to provide credentials again regardless of whether or not a previous session exists. I didn't logged out or closed browser but its asking authentication for every application.

I've CAS Server 4.0 and Client 3.4.1 versions and also configured CAS client in web.xml of my each application as below.

**In web.xml**

```
<filter>
    <filter-name>CAS Single Sign Out Filter</filter-name>
    <filter-class>org.jasig.cas.client.session.SingleSignOutFilter</filter-class>
    <init-param>
        <param-name>casServerUrlPrefix</param-name>
        <param-value>http://localhost:8080/cas</param-value> 
    </init-param>
</filter>
<filter-mapping>
    <filter-name>CAS Single Sign Out Filter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>

<listener>
    <listener-class>org.jasig.cas.client.session.SingleSignOutHttpSessionListener
    </listener-class>
</listener>

<filter>
    <filter-name>CAS Authentication Filter</filter-name>
    <filter-class>org.jasig.cas.client.authentication.AuthenticationFilter</filter-class>
    <init-param>
        <param-name>casServerLoginUrl</param-name>
        <param-value>http://localhost:8080/cas/login</param-value>
    </init-param>
    <init-param>
        <param-name>serverName</param-name>
        <param-value>http://localhost:8080</param-value>
    </init-param>
    <init-param>
        <param-name>gateway</param-name>
        <param-value>false</param-value>
    </init-param>
</filter>
<filter>
    <filter-name>CAS Validation Filter</filter-name>
    <filter-class>org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter</filter-class>
    <init-param>
        <param-name>casServerUrlPrefix</param-name>
        <param-value>http://localhost:8080/cas</param-value>
    </init-param>
    <init-param>
        <param-name>serverName</param-name>
        <param-value>http://localhost:8080</param-value>
    </init-param>
</filter>

<filter>
    <filter-name>CAS HttpServletRequest Wrapper Filter</filter-name>
    <filter-class>org.jasig.cas.client.util.HttpServletRequestWrapperFilter</filter-class>
</filter>

<filter>
    <filter-name>CAS Assertion Thread Local Filter</filter-name>
    <filter-class>org.jasig.cas.client.util.AssertionThreadLocalFilter</filter-class>
</filter>

<filter-mapping>
    <filter-name>CAS Authentication Filter</filter-name>
    <url-pattern>/login.do</url-pattern>
</filter-mapping>

<filter-mapping>
    <filter-name>CAS Validation Filter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>

<filter-mapping>
    <filter-name>CAS HttpServletRequest Wrapper Filter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>

<filter-mapping>
    <filter-name>CAS Assertion Thread Local Filter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>

<filter-mapping>
    <filter-name>CAS Validation Filter</filter-name>
    <url-pattern>/proxyCallback</url-pattern>
</filter-mapping>
<context-param>
    <param-name>renew</param-name>
    <param-value>false</param-value>
</context-param>
```

**Comment by battags** [comment]
Single sign only works over https. You are redirecting to CAS over http.

**Comment by satya410** [comment]
First thanks for your response. 

Exactly CAS 4 will not work on HTTP by default. To work on HTTP I changed cookieSecure="false" in ticketGrantingTicketCookieGenerator.xml. Now issue is, if I logged in app1, in app2 and app3 its not asking authentication. I opened all three applications in separate tabs (authenticated only once). If I logged out in app2, TGT is destroyed and I successfully logged out of my app2 (its showing login page here) and app3 (just refreshed here its showing login page) but in app1 (after refreshing here still it showing as logged in page not login page) means session is not destroyed in app1. SSO is working but SLO is not working. What changes are required.

**Comment by satya410** [comment]
With continuation of my discussion, I debug CAS Server its showing as below 

[org.jasig.cas.CentralAuthenticationServiceImpl] - <Removing ticket [TGT-1-BEacZ4CpvMRxgSY5lEb5xvnGQ9fLgPjKJcjXj3BMKHjbQXCGJM-org.in] from registry.>
[org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Attempting to retrieve ticket [TGT-1-BEacZ4CpvMRxgSY5lEb5xvnGQ9fLgPjKJcjXj3BMKHjbQXCGJM-org.in]>
[org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Ticket [TGT-1-BEacZ4CpvMRxgSY5lEb5xvnGQ9fLgPjKJcjXj3BMKHjbQXCGJM-org.in] found in registry.>
[org.jasig.cas.CentralAuthenticationServiceImpl] - <Ticket found. Processing logout requests and then deleting the ticket...>

[org.jasig.cas.logout.SamlCompliantLogoutMessageCreator] - <Generated logout message: [<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="LR-1-UyEndFd1pcdVLlfnYvgTtoHWxnfuyewXC0O" Version="2.0" IssueInstant="2017-06-20T16:29:46Z"><saml:NameID xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">@NOT_USED@</saml:NameID><samlp:SessionIndex>ST-2-jp9ydEyiFuT9hlKw2SaK-org.in</samlp:SessionIndex></samlp:LogoutRequest>]>
[org.jasig.cas.logout.LogoutManagerImpl] - <Sending logout request for: [http://abc.in:8888/app1/login.do]>
[org.jasig.cas.util.SimpleHttpClient] - <Attempting to access http://abc.in:8888/app1/login.do>

[org.jasig.cas.logout.SamlCompliantLogoutMessageCreator] - <Generated logout message: [<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="LR-2-f4WoyqJZXDeNEBvKC01v3wgegUixizaiNVq" Version="2.0" IssueInstant="2017-06-20T16:29:46Z"><saml:NameID xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">@NOT_USED@</saml:NameID><samlp:SessionIndex>ST-1-DLttZgFyzfWmdpXVmB4a-org.in</samlp:SessionIndex></samlp:LogoutRequest>]>
[org.jasig.cas.logout.LogoutManagerImpl] - <Sending logout request for: [http://abc.in:8888/app3/login.do]>
[org.jasig.cas.util.SimpleHttpClient] - <Attempting to access http://abc.in:8888/app3/login.do>

[org.jasig.cas.logout.SamlCompliantLogoutMessageCreator] - <Generated logout message: [<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="LR-3-aB17Lg0jm7pcLqXi4v2Srs1Ujq1bSCimmT9" Version="2.0" IssueInstant="2017-06-20T16:29:46Z"><saml:NameID xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">@NOT_USED@</saml:NameID><samlp:SessionIndex>ST-3-1tiTu9pcVaNs55O7FX4m-org.in</samlp:SessionIndex></samlp:LogoutRequest>]>
[org.jasig.cas.logout.LogoutManagerImpl] - <Sending logout request for: [http://abc.in:8888/app2/login.do]>

[org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Removing ticket [TGT-1-BEacZ4CpvMRxgSY5lEb5xvnGQ9fLgPjKJcjXj3BMKHjbQXCGJM-org.in] from registry>
[org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Attempting to retrieve ticket [TGT-1-BEacZ4CpvMRxgSY5lEb5xvnGQ9fLgPjKJcjXj3BMKHjbQXCGJM-org.in]>

[org.jasig.cas.util.SimpleHttpClient] - <Attempting to access http://abc.in:8888/app2/login.do>

[org.jasig.cas.web.support.CookieRetrievingCookieGenerator] - <Removed cookie with name [TGC]>
[org.jasig.cas.web.support.CookieRetrievingCookieGenerator] - <Removed cookie with name [CASPRIVACY]>

[org.jasig.cas.util.SimpleHttpClient] - <Finished sending message to http://abc.in:8888/app1/login.do>
[org.jasig.cas.util.SimpleHttpClient] - <Finished sending message to http://abc.in:8888/app2/login.do>
[org.jasig.cas.util.SimpleHttpClient] - <Finished sending message to http://abc.in:8888/app3/login.do>

[com.github.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN

WHO: audit:unknown
WHAT: TGT-1-BEacZ4CpvMRxgSY5lEb5xvnGQ9fLgPjKJcjXj3BMKHjbQXCGJM-org.in
ACTION: TICKET_GRANTING_TICKET_DESTROYED
APPLICATION: CAS
WHEN: Tue Jun 20 16:29:46 IST 2017
CLIENT IP ADDRESS: 10.191.53.54
SERVER IP ADDRESS: 10.191.53.54

Here issue is, if I logged out of my app1 its logged out from app1 and app3 but I'm unable to logged out from app2. Still session is alive. I'm using same CAS client configuration in all the three applications. Here I opened all the three applications in separate tabs. What is the exact issue.
