### ISSUE TITLE
No cas-client-integration-tomcat-v8 artifact at Maven Central

### ISSUE THREAD

**Issue by mwoodiupui** [apereo/java-cas-client#221]
Neither search.maven.org nor mvnrepository.com can find it.  v6 and v7 are visible at Central.

**Comment by mmoayyed** [comment]
Chances are, it's because it's not released yet and will be at due time. Thanks for the report.

**Comment by mwoodiupui** [comment]
Release 3.4.1 claims that this was included, from #151.
https://github.com/apereo/java-cas-client/releases/tag/cas-client-3.4.1
