### ISSUE TITLE
A very poor design of heavy and dull

### ISSUE THREAD

**Issue by xingzhefeng** [apereo/java-cas-client#229]
```
public abstract class AbstractUrlBasedTicketValidator implements TicketValidator {
    protected final Log log = LogFactory.getLog(this.getClass());
    private final String casServerUrlPrefix;
    private boolean renew;
    private Map customParameters;
```
the Subsystem not just only one casServer .
For example, we use it
login.xxx.com  
login.xxx.net
login.yyy.cn 
now,We can only rewrite Validator .

**Comment by serac** [comment]
If you'd like to attempt to clarify your criticism further into something actionable, please feel free to do so. Without further information, however, we're obliged to close the issue.
