### ISSUE TITLE
Is there any C/S application demo show how to use java-cas-client?

### ISSUE THREAD

**Issue by yuanjinyong** [apereo/java-cas-client#233]
As many of REST api in java backend application is ajax request for frontend (eg Single Page Application or Android APP, IOS APP), and it can't redirect to the login page. 
The login screen is not from the cas server, is from the fronted, and fronted send a ajax login request to backend with username and password, the backend how to authentication by use CAS REST API? And how to return the TGT to frontend?
Is there any demos?

**Comment by mmoayyed** [comment]
Not issue. Hop onto the mailing list and ask please.
