### ISSUE TITLE
SingleSignOutHandler.casServerUrlPrefix is not used

### ISSUE THREAD

**Issue by larsgrefer** [apereo/java-cas-client#329]
`org.jasig.cas.client.session.SingleSignOutHandler` logs a warning when `casServerUrlPrefix` is not set:

>Front Channel single sign out redirects are disabled when the 'casServerUrlPrefix' value is not set.

I think this warning is wrong, because `casServerUrlPrefix` isn't used anywhere in the code (except for throwing an exception when its null and logging the warning when its blank)

**Comment by larsgrefer** [comment]
Why would you just close an error report?

**Comment by larsgrefer** [comment]
@mmoayyed Why is your bot just closing all issues?

**Comment by mmoayyed** [comment]
The bot dislikes inactivity. If there is nothing to be done, there is nothing to fix and there is no issue. You are more than welcome to post patch to fix what you deem to be an issue.
