### ISSUE TITLE
Support JBoss 7 JNDI configuration lookup 

### ISSUE THREAD

**Issue by magrossmann** [apereo/java-cas-client#60]
In JBoss 7 the naming conventions for JNDI bindings changed a bit.
CAS Client searches for "java:comp/env/cas/" bindings.
This is not possible anymore. The JNDI Path has to start with "java:/" or use the global path "java:global/"

The lookup is defined in AbstractConfigurationFilter.

Is there a chance that this will be adjusted in one of the next versions?

**Comment by torres-sgd** [comment]
You can use the context parameter "configurationStrategy" to setup directly the class: "org.jasig.cas.client.configuration.JBossCompatibleJndiConfigurationStrategyImpl", you will need to get the cas-client-integration-jboss 3.4.1 jar library from maven.

This configuration Strategy change the path to be abble for read the parameters.
