### ISSUE TITLE
should we support load some settings from classpath file?

### ISSUE THREAD

**Issue by icanfly** [apereo/java-cas-client#98]
hi, I'm meeting some problems with this client, I'm using servlet 3.0 , I want to put configurations of cas client listeners/filters  into a /META-INF/web-fragment.xml in a seperate jar file that if one project only dependency this jar  and it has the ability of cas sso.  so, now , the only thing is that cas java client should support config file from classpath or somewhere ?
I have found that it can be resovle by using JNDI style configuration, but I think it's not good enough.

**Comment by leleuj** [comment]
You can load configuration in multiple ways: https://github.com/Jasig/java-cas-client/tree/master/cas-client-core/src/main/java/org/jasig/cas/client/configuration. And especially from a properties file.

**Comment by icanfly** [comment]
ok, tks.  I'm using old version , I have got it. It's better to use newer version.
should it can be load from  classpath:/cas-java-client.properties ?  like spring classpath context ?
I think it easy to do .
I made a pull , you can check it 
https://github.com/Jasig/java-cas-client/pull/99

**Comment by mmoayyed** [comment]
So why cant you simply put the client config into a web.xml-like file and have it be loaded from classpath?
